# Generated by Django 5.0.3 on 2024-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('code', models.SmallIntegerField(verbose_name='کد ( یک کد چهار رقمی است که به تلفن کاربر ارسال می\u200cشود , در مرحله رجیستر کردن )')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کد',
                'verbose_name_plural': 'کد های پیامکی',
            },
        ),
    ]
