# Generated by Django 5.0.3 on 2024-09-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunavbar',
            name='sub_menu',
            field=models.BooleanField(default=False),
        ),
    ]
