# Generated by Django 5.0.3 on 2024-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0006_contactus_email_alter_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
