# Generated by Django 5.0.3 on 2024-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0008_replycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('a', 'پشتیبانی فنی'), ('b', 'سوالات درباره محصولات'), ('c', 'مشکلات حساب کاربران'), ('d', 'نظرات و پیشنهادات'), ('e', 'شکایت و انتقاد'), ('f', 'همکاری و شراکت'), ('g', 'درخواست اطلاعات بیشتر'), ('h', 'پرسش\u200cهای عمومی')], max_length=255),
        ),
    ]
