# Generated by Django 5.0.3 on 2024-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0011_alter_contactus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
