# Generated by Django 5.0.3 on 2024-08-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0012_tag_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
