# Generated by Django 5.0.3 on 2024-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0013_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='reply_complete',
            field=models.BooleanField(default=False),
        ),
    ]
