# Generated by Django 5.0.3 on 2024-06-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to='baner_category'),
        ),
    ]
