# Generated by Django 5.0.3 on 2024-07-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_category_is_sub_remove_category_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'زیر دسته بندی', 'verbose_name_plural': 'زیر دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('off', 'تخفیف'), ('definite', 'مقطوع')], default='definite', max_length=12),
        ),
    ]
