# Generated by Django 5.0.3 on 2024-08-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_product_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_by',
            field=models.IntegerField(default=0),
        ),
    ]
